services:
  - type: web
    name: smc-scalp-server
    env: docker
    build:
      context: server
      dockerfile: Dockerfile
    envVars:
      - key: FCM_PROJECT_ID
        value: smc-scalp
      - key: FCM_SERVICE_ACCOUNT_JSON
        sync: false